//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.18 at 01:29:05 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:mFlow",xmlns =@XmlNs(prefix = "urn",namespaceURI = "urn:mFlow"))
package ru.credit_history_service.xsd;

import javax.xml.bind.annotation.XmlNs;